import { Inter } from "next/font/google";
import 'devextreme/dist/css/dx.light.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import "@/styles/globals.css";
import BtnAppBar from "@/layout/appBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body className={inter.className}>
        <div className="flex  md:my-20 ">
          
            <BtnAppBar />
            {children}
          
        </div>
      </body>
    </html>
  );
}
